# 注意,冒号后面有一个空格
modelUrl: http://localhost:8080/answer


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true&autoReconnect=true
    username: mysql
    password: mysql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志
#  global-config:
#    db-config:
#      id-type: auto # 主键自增
file:
  upload:
    allowed-extensions: txt  # 默认只允许txt
    max-size: 10MB          # 单个文件最大大小
    location: ./uploads      # 文件存储目录

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none